Nsm\Bundle\ApiBundle\Entity\Project:
    type: entity
    repositoryClass: Nsm\Bundle\ApiBundle\Entity\ProjectRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        description:
            type: text
            nullable: true
        taskDurationSum:
            type: decimal
            scale: 2
        createdAt:
            type: datetime
            nullable: true
        updatedAt:
            type: datetime
            nullable: true
        deletedAt:
            type: datetime
            nullable: true

    oneToMany:
        tasks:
            targetEntity: Task
            mappedBy: project
            cascade:
                - persist
                - remove
        features:
            targetEntity: Feature
            mappedBy: project
            cascade:
                - remove
