Nsm\Bundle\AppBundle\Entity\Project:
    exclusion_policy: ALL
    xml_root_name: project
    max_depth: 2
    custom_accessor_order:
        - id
    properties:
        title:
            expose: true
        description:
            expose: true
        taskDurationSum:
            expose: true
    relations:
        -
            rel: self
            href:
                route: project_read
                parameters:
                    id: 'expr(object.getId())'
        -
            rel: tasks
            href:
                route: task_browse
                parameters:
                    project: expr(object.getId())
            embedded:
                content: expr(object.getTasks())
                xmlElementName: tasks
