Nsm\Bundle\AppBundle\Entity\Task:
    exclusion_policy: ALL
    xml_root_name: task
    custom_accessor_order:
        - id
    properties:
        title:
            expose: true
        description:
            expose: true
        activityDurationSum:
            expose: true
    relations:
        -
            rel: self
            href:
                route: task_read
                parameters:
                    id: expr(object.getId())
        -
            rel: project
            href:
                route: project_read
                parameters:
                    id: expr(object.getProject().getId())
            embedded:
                content: expr(object.getProject())
                xmlElementName: project
        -
            rel: activities
            href:
                route: activity_browse
                parameters:
                    task: expr(object.getId())
            embedded:
                content: expr(object.getActivities())
                xmlElementName: activities

