parameters:
    knp.doctrine_behaviors.blameable_listener.user_entity: Nsm\Bundle\UserBundle\Entity\User
#    knp.doctrine_behaviors.timezoneable_listener.user_entity: Nsm\Bundle\UserBundle\Entity\User

imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: ../../vendor/knplabs/doctrine-behaviors/config/orm-services.yml }

services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
#            - form_table_layout.html.twig
#            - NsmFormBundle:Form:form_div_layout.html.twig
            - NsmFormBundle:Form:form_table_layout.html.twig

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        types:
            timezone: Nsm\Bundle\ApiBundle\Doctrine\DBAL\Types\TimeZoneType
            datetime: Nsm\Bundle\ApiBundle\Doctrine\DBAL\Types\UTCDateTimeType
        mapping_types:
            timezone: string
#            utcdatetime: string
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                auto_mapping: true
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true

stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            timestampable: true
            softdeleteable: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

sensio_framework_extra:
    request: 
        converters: true
    view:
        annotations: false
    router:
        annotations: true

nelmio_api_doc: ~

fos_rest:
    routing_loader:
        include_format: true
    body_converter:
        enabled: true
    param_fetcher_listener: force
    body_listener: true
    format_listener:
        rules:
            - { path: '^/', priorities: ['json', html, '*/*'], fallback_format: json, prefer_extension: true }
    view:
        view_response_listener: force
        serialize_null: true
        force_redirects:
            html: true
    serializer:
        serialize_null: true

jms_serializer:
    metadata:
        directories:
            NsmApiBundle:
                namespace_prefix: "Nsm\\Bundle\\ApiBundle"
                path: "@NsmApiBundle/Resources/config/serializations"

bazinga_hateoas: ~

nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['*']
        allow_headers: ['Origin', 'X-Requested-With', 'Content-Type', 'Accept']
        allow_methods: ['POST','GET','DELETE','PUT','PATCH']
        expose_headers: ['*']
        max_age: 0
    paths:
      '^/': ~

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Nsm\Bundle\UserBundle\Entity\User
    registration:
        form:
            type: nsm_user_user_registration

nsm_postmark:
    api_key: b2ad7cb0-a326-429b-b307-b794d4dfb458
    inbound_reply_address: ba68058e7fec66b301f0542b3f1d1983@inbound.postmarkapp.com
