NsmUserBundle:
    resource: "@NsmUserBundle/Resources/config/routing.yml"

NsmApiBundle:
    resource: "@NsmApiBundle/Resources/config/routing.yml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

NsmApiBundle:
    resource: "@NsmApiBundle/Resources/config/routing.yml"
    prefix:   /
