Nsm\Bundle\AppBundle\Entity\Invitation:
    properties:
        title:
            - NotBlank: ~
        code:
            - NotNull: ~
            - Email: ~
        email:
            - NotNull: ~
            - Email: ~
        expiresAt:
            - Date: ~
        claimedAt:
            - Date: ~
        createdAt:
            - Date: ~
        updatedAt:
            - Date: ~
        deletedAt:
            - Date: ~
